version: '3.8'

services:
  app:
    build: .
    container_name: datawow_test_web
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
